<?php

	/**
	 * Model {$table}
	 * 
	 * AutoGenerated Model from Database
	 * 
	 * @author Wiz Interactive
	 */
	class {$table} extends model
	{

		public $_table = '{$table}';
		public $_sql_create = "{$createSQL}";

		{$fields}

		public function listPaged(&$get)
		{
			uses('util','modelfields');

			$page = (empty($get['page'])) ? 1 : $get['page'];
			unset($get['page']);

			$sortField = (empty($get['sortField'])) ? 'id' : $get['sortField'];
			unset($get['sortField']);

			$sortDirection = (empty($get['sortDirection'])) ? 'asc' : $get['sortDirection'];
			unset($get['sortDirection']);

			$options = array();
			$options['order'] = "$sortField $sortDirection";
			{$langCondition}

			foreach($get as $field=>$value) {
				if(!empty($value)) {
					$options['conditions'][] = sprintf($this->getFilterConditionByField($field),$value);
				}
			}



			$numRows = $this->count($options);

			$pager = sBook::Pager($page, $numRows, ROWS_PER_PAGE, PAGES_PER_GROUP);

			$options['offset']	= $pager['offset'];
			$options['limit']	= $pager['limit'];

			$ret = array(
				'rows'			=> $this->findAll($options, true),
				'pager'			=> $pager,
				'sortField'		=> $sortField,
				'sortDirection'	=> $sortDirection
			);

			return $ret;

		}

		private function getFilterConditionByField($field)
		{
			switch($field)
			{
				{$conditionNumber}
					$condition = "$field = %d";
					break;

				{$conditionExact}
					$condition = "$field = '%s'";
					break;

				{$conditionLike}
					$condition = "$field LIKE '%%%s%%'";
					break;
				}
				return $condition;
		}
	}